In [1]:
import pandas as pd
import numpy as np
import sqlite3
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

## import des données

base de 2022 => 32k lignes entre le 01/01/22 et le 23/11/22

In [2]:
df = pd.read_csv('data/2022_chouwal.csv')

/var/folders/_9/mhh0zmd566jf32g8nqp6r06h0000gn/T/ipykernel_47982/1087890924.py:1: DtypeWarning: Columns (17,20,23,24,63,106,108,110,111,127,133,134,139,146,151,153,154,156,157,161,162,168,171) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/2022_chouwal.csv')

## tri des données : on supprime les colonnes vides ou jugées non pertinentes

In [3]:
df.drop_duplicates()

,id,comp,jour,hippo,numcourse,cl,dist,partant,typec,cheque,...,forceVent,directionVent,nebulositeLibelleCourt,condi,url,tempscourse,updatedAt,createdAt,devise.1,ref
0,141182911,1411829,2022-11-24,Mons,1411829,NaN,1500,11,Plat,4000,...,0,NaN,NaN,"Pour poulains entiers, hongres et pouliches de...",https://www.paris-turf.com/course/-idc-210300f...,NaN,NaN,2022-11-23 01:17:35,EUR,NaN
1,141182910,1411829,2022-11-24,Mons,1411829,NaN,1500,11,Plat,4000,...,0,NaN,NaN,"Pour poulains entiers, hongres et pouliches de...",https://www.paris-turf.com/course/-idc-210300f...,NaN,NaN,2022-11-23 01:17:35,EUR,NaN
2,141182814,1411828,2022-11-24,Mons,1411828,NaN,1500,14,Plat,7000,...,0,NaN,NaN,"Pour chevaux entiers, hongres et juments de 3 ...",https://www.paris-turf.com/course/-idc-777bc9b...,NaN,NaN,2022-11-23 01:17:01,EUR,31.5
3,141182813,1411828,2022-11-24,Mons,1411828,NaN,1500,14,Plat,7000,...,0,NaN,NaN,"Pour chevaux entiers, hongres et juments de 3 ...",https://www.paris-turf.com/course/-idc-777bc9b...,NaN,NaN,2022-11-23 01:17:01,EUR,31.5
4,141182812,1411828,2022-11-24,Mons,1411828,NaN,1500,14,Plat,7000,...,0,NaN,NaN,"Pour chevaux entiers, hongres et juments de 3 ...",https://www.paris-turf.com/course/-idc-777bc9b...,NaN,NaN,2022-11-23 01:17:01,EUR,31.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32950,13989215,1398921,2022-11-01,Angoulême,1398921,2,4200,7,Plat,13000,...,11,South-,nuageux,"Pour tous chevaux de 5 ans et au-dessus, n'aya...",https://www.paris-turf.com/course/-idc-3f02c25...,"6'1201""",NaN,2022-11-02 23:11:55,EUR,NaN
32951,13989214,1398921,2022-11-01,Angoulême,1398921,3,4200,7,Plat,13000,...,11,South-,nuageux,"Pour tous chevaux de 5 ans et au-dessus, n'aya...",https://www.paris-turf.com/course/-idc-3f02c25...,"6'1201""",NaN,2022-11-02 23:11:55,EUR,NaN
32952,13989213,1398921,2022-11-01,Angoulême,1398921,7,4200,7,Plat,13000,...,11,South-,nuageux,"Pour tous chevaux de 5 ans et au-dessus, n'aya...",https://www.paris-turf.com/course/-idc-3f02c25...,"6'1201""",NaN,2022-11-02 23:11:55,EUR,NaN
32953,13989212,1398921,2022-11-01,Angoulême,1398921,5,4200,7,Plat,13000,...,11,South-,nuageux,"Pour tous chevaux de 5 ans et au-dessus, n'aya...",https://www.paris-turf.com/course/-idc-3f02c25...,"6'1201""",NaN,2022-11-02 23:11:55,EUR,NaN
32954,13989211,1398921,2022-11-01,Angoulême,1398921,1,4200,7,Plat,13000,...,11,South-,nuageux,"Pour tous chevaux de 5 ans et au-dessus, n'aya...",https://www.paris-turf.com/course/-idc-3f02c25...,"6'1201""",NaN,2022-11-02 23:11:55,EUR,NaN

In [4]:
db = df.drop(columns = ["id", "comp", "jour","hippo", "heure", "numcourse", "cheval", "commen", "gainsCarriere", "gainsVictoires", "gainsPlace", "gainsAnneeEnCours", "gainsAnneePrecedente", "jumentPleine", "engagement", "handicapDistance", "handicapPoids", "indicateurInedit", "tempstot", "vha", "recordG", "recordGint", "txreclam", "dernierTxreclam", "createdat", "updatedat", "dernierTxreclam", "rangTxVictJock", "rangTxVictCheval", "rangTxVictEnt", "rangTxPlaceJock", "rangTxPlaceCheval", "rangTxPlaceEnt", "rangRecordG", "appetTerrain", "estSupplemente", "devise", "coat", "country", "id", "comp", "jour", "heure", "hippo", "reun", "prix", "prixnom", "partant", "groupe", "autos", "quinte", "arriv", "lice", "url", "updatedAt", "createdAt", "devise","id.1", "comp.1", "jour.1", "hippo.1", "typec.1", "partant.1", "dist.1", "devise.1", "corde.1", "age.1", "cheque.1"       ])

### modèle brut => sans étude du passé du cheval

In [5]:
#db.to_csv('data/2022_chouwal_filtered_1.csv')

On vire des trucs potentiellement intéressants, en rapport avec la course

In [6]:
db = db.drop(columns = [ "europ", "natpis", "amat", "courseabc", "pistegp", "temperature", "forceVent", "directionVent", "nebulositeLibelleCourt", "condi", "tempscourse", "ref"])

maintenant, on vire des trucs potentiellement intéressant, en rapport avec le cheval

In [7]:
db = db.drop(columns = ["numero","ecurie", "distpoids", "ecar", "redkm", "redkmInt", "corde", "musiquept", "musiqueche", "jockey", "musiquejoc", "montesdujockeyjour", "couruejockeyjour", "victoirejockeyjour", "entraineur", "musiqueent", "dernierhippo", "derniernbpartants","dernierJoc", "dernierEnt", "dernierProp", "dernierRedKm", "proprietaire", "pere", "mere", "peremere", "meteo", "handi", "reclam", "sex", "sexe", "age", "defoeil", "defoeilPrec", "derniereplace", "oeil", "dernierOeil", "typec"])

## Prépararation dataset => cl devient category

In [8]:
db.dropna(subset=['cl'], inplace = True) # on vire les lignes dont les résultats ne sont pas connus

In [9]:
db.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29396 entries, 239 to 32954
Data columns (total 61 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   cl                      29396 non-null  object
 1   dist                    29396 non-null  int64
 2   cheque                  29396 non-null  int64
 3   cotedirect              29396 non-null  float64
 4   coteprob                29396 non-null  float64
 5   recence                 29396 non-null  int64
 6   recul                   29396 non-null  int64
 7   gains                   29396 non-null  int64
 8   m1                      29396 non-null  int64
 9   m2                      29396 non-null  int64
 10  m3                      29396 non-null  int64
 11  m4                      29396 non-null  int64
 12  m5                      29396 non-null  int64
 13  m6                      29396 non-null  int64
 14  monteentraineurjour     29396 non-null  int64
 15  courueentraineurjour    29396 non-null  int64
 16  victoireentraineurjour  29396 non-null  int64
 17  coursescheval           29396 non-null  int64
 18  victoirescheval         29396 non-null  int64
 19  placescheval            29396 non-null  int64
 20  coursesentraineur       29396 non-null  int64
 21  victoiresentraineur     29396 non-null  int64
 22  placeentraineur         29396 non-null  int64
 23  coursesjockey           29396 non-null  int64
 24  victoiresjockey         29396 non-null  int64
 25  placejockey             29396 non-null  int64
 26  dernierealloc           29396 non-null  int64
 27  dernieredist            29396 non-null  int64
 28  dernierecote            29396 non-null  float64
 29  nbcoursepropjour        29396 non-null  int64
 30  poidmont                12791 non-null  float64
 31  pourcVictJock           29396 non-null  float64
 32  pourcPlaceJock          29396 non-null  float64
 33  pourcVictCheval         29396 non-null  float64
 34  pourcPlaceCheval        29396 non-null  float64
 35  pourcVictEnt            29396 non-null  float64
 36  pourcPlaceEnt           29396 non-null  float64
 37  pourcVictEntHippo       29396 non-null  float64
 38  pourcVictJockHippo      29396 non-null  float64
 39  pourcPlaceEntHippo      29396 non-null  float64
 40  pourcPlaceJockHippo     29396 non-null  float64
 41  pourcVictChevalHippo    29396 non-null  float64
 42  pourcPlaceChevalHippo   29396 non-null  float64
 43  nbrCourseJockHippo      29396 non-null  int64
 44  nbrCourseEntHippo       29396 non-null  int64
 45  nbrCourseChevalHippo    29396 non-null  int64
 46  nbCourseCouple          29396 non-null  int64
 47  nbVictCouple            29396 non-null  int64
 48  nbPlaceCouple           29396 non-null  int64
 49  TxVictCouple            29396 non-null  float64
 50  TxPlaceCouple           29396 non-null  float64
 51  nbCourseCoupleHippo     29396 non-null  int64
 52  nbVictCoupleHippo       29396 non-null  int64
 53  nbPlaceCoupleHippo      29396 non-null  int64
 54  TxVictCoupleHippo       29396 non-null  float64
 55  TxPlaceCoupleHippo      29396 non-null  float64
 56  idChe                   29396 non-null  int64
 57  idJockey                29396 non-null  int64
 58  idEntraineur            29396 non-null  int64
 59  defFirstTime            29396 non-null  int64
 60  oeilFirstTime           29370 non-null  float64
dtypes: float64(21), int64(39), object(1)
memory usage: 13.9+ MB

In [10]:
db.cl.value_counts()

1      2788
2      2787
3      2777
4      2748
5      2655
6      2516
DAI    2416
7      2301
8      2014
9      1671
10     1342
11      956
12      653
ARR     590
13      413
14      270
TBE     127
15      119
TJ       71
16       63
17       17
JT       15
3DI       8
RP        8
18        7
2DI       7
DER       4
7DI       4
1D        4
4DI       4
1DI       4
6DI       4
7D        4
5DI       4
20        3
21        3
19        3
4D        3
8DI       2
DIS       2
3D        2
3DP       2
22        1
8D        1
5D        1
10D       1
6D        1
Name: cl, dtype: int64

In [11]:
mask = db['cl'].str.isnumeric()
db['cl'][mask == False] = 999
db.cl = pd.to_numeric(db.cl, errors='coerce') # on convertit toutes les valeurs en valeur int
mask1 = db['cl'] < 4
db['cl'][mask1 == True] = 1 # tous les placés (podiums) prennent la valeur 1
mask2 = db['cl'] > 1
db['cl'][mask2 == True] = 0 # tous les hors podium prennent la valeur 0

/var/folders/_9/mhh0zmd566jf32g8nqp6r06h0000gn/T/ipykernel_47982/3208879561.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  db['cl'][mask == False] = 999
/var/folders/_9/mhh0zmd566jf32g8nqp6r06h0000gn/T/ipykernel_47982/3208879561.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  db['cl'][mask1 == True] = 1 # tous les placés (podiums) prennent la valeur 1
/var/folders/_9/mhh0zmd566jf32g8nqp6r06h0000gn/T/ipykernel_47982/3208879561.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  db['cl'][mask2 == True] = 0 # tous les hors podium prennent la valeur 0

## Baseline model :   
Nombre de valeurs 1 (placés) sur le nombre de valeurs totales

In [12]:
db.cl.value_counts()[1]/(db.cl.value_counts()[0] + db.cl.value_counts()[0])

0.19844136095799278

## Premier model: PCA + logistic regression

### Definition of X and y + Scaling

In [13]:
X = db.drop(columns = "cl")
y = db.cl
features = X.columns

#⚠️ Data must be centered around its mean before applying PCA ⚠️
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

imputer = SimpleImputer()
imputer.fit(X)
X = imputer.transform(X)

X = pd.DataFrame(X, columns=features)

In [18]:
X

,dist,cheque,cotedirect,coteprob,recence,recul,gains,m1,m2,m3,...,nbCourseCoupleHippo,nbVictCoupleHippo,nbPlaceCoupleHippo,TxVictCoupleHippo,TxPlaceCoupleHippo,idChe,idJockey,idEntraineur,defFirstTime,oeilFirstTime
0,-1.690946,1.183463,-0.390301,-0.405199,-0.247013,-0.32613,1.519476,-0.433174,-1.124233,1.359248,...,-0.341868,-0.231219,-0.298502,-0.278190,-0.448752,-0.761029,0.581590,2.119006,-0.098241,-0.127526
1,-1.690946,1.183463,-0.104155,-0.405199,1.660853,-0.32613,0.816650,-0.980597,-0.052700,-0.761259,...,-0.341868,-0.231219,-0.298502,-0.278190,-0.448752,0.310319,0.704510,2.448548,-0.098241,-0.127526
2,-1.690946,1.183463,-0.068386,-0.405199,-0.247013,-0.32613,0.994296,1.756516,-0.320583,0.564058,...,-0.341868,-0.231219,-0.298502,-0.278190,-0.448752,0.171582,2.315707,-0.964012,-0.098241,-0.127526
3,-1.690946,1.183463,-0.261535,-0.405199,-0.108618,-0.32613,1.135076,-0.433174,-0.856349,1.889374,...,0.106783,0.887245,0.235146,2.577239,1.282297,0.153795,-0.412176,0.842097,-0.098241,-0.127526
4,1.422252,-0.228053,-0.247228,-0.083240,-0.237127,-0.32613,-0.150863,-0.706886,-0.320583,1.359248,...,-0.341868,-0.231219,-0.298502,-0.278190,-0.448752,0.487351,0.180396,-1.464538,-0.098241,-0.127526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29391,2.293948,-0.242757,-0.461837,-0.405199,-0.335981,-0.32613,-0.194100,1.209093,-0.320583,0.298994,...,-0.117543,-0.231219,0.235146,-0.278190,3.013347,-1.064120,-0.218194,-1.195063,-0.098241,-0.127526
29392,2.293948,-0.242757,-0.461837,-0.405199,-0.256898,-0.32613,-0.226949,-1.254308,-0.052700,1.359248,...,-0.341868,-0.231219,-0.298502,-0.278190,-0.448752,-0.079310,0.869412,-0.096421,-0.098241,-0.127526
29393,2.293948,-0.242757,-0.461837,-0.405199,-0.256898,-0.32613,-0.180644,1.209093,-0.588466,-0.231132,...,-0.341868,-0.231219,-0.298502,-0.278190,-0.448752,0.239702,1.777464,-0.096421,-0.098241,-0.127526
29394,2.293948,-0.242757,-0.461837,-0.405199,-0.335981,-0.32613,0.299221,-0.706886,-0.856349,-0.496196,...,-0.341868,-0.231219,-0.298502,-0.278190,-0.448752,-1.502920,1.849798,-0.840399,-0.098241,-0.127526
29395,2.293948,-0.242757,-0.372416,-0.405199,-0.197586,-0.32613,-0.135132,-1.254308,-1.124233,-1.026322,...,-0.341868,-0.231219,-0.298502,-0.278190,-0.448752,-0.514840,1.618938,-0.723820,-0.098241,-0.127526

In [14]:
pca = PCA()
pca.fit(X)

PCA()

In [15]:
X_proj = pca.transform(X)
X_proj = pd.DataFrame(X_proj, columns=[f'PC{i}' for i in range(1, features.size + 1)])

In [16]:
model.fit(X_proj, y)

NameError: name 'model' is not defined